/* Generated by tools/wf_lexgen.py; do not edit. */
#ifndef WOLFRAM_ATPROTO_LEX_H
#define WOLFRAM_ATPROTO_LEX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <wolfram/xrpc.h>
#include <wolfram/auth_client.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Encoded JSON view. Decoded outputs own data; input values borrow it. */
typedef struct wf_lex_json { const char *data; size_t length; } wf_lex_json;
/** Byte sequence view. Decoded outputs own data; input values borrow it. */
typedef struct wf_lex_bytes { const uint8_t *data; size_t length; } wf_lex_bytes;
/** CID link string view. */
typedef struct wf_lex_cid_link { const char *cid; } wf_lex_cid_link;
/** Typed AT Protocol blob reference. */
typedef struct wf_lex_blob { const char *cid; const char *mime_type; int64_t size; } wf_lex_blob;
#define WF_LEX_ARRAY(type_) struct { type_ const *items; size_t count; }

/** Resolves an atproto handle (hostname) to a DID. Does not necessarily bi-directionally verify against the the DID document. */
#define WF_LEX_COM_ATPROTO_IDENTITY_RESOLVE_HANDLE_NSID "com.atproto.identity.resolveHandle"
#define WF_LEX_COM_ATPROTO_IDENTITY_RESOLVE_HANDLE_KIND "query"

/** Apply a batch transaction of repository creates, updates, and deletes. Requires auth, implemented by PDS. */
#define WF_LEX_COM_ATPROTO_REPO_APPLY_WRITES_NSID "com.atproto.repo.applyWrites"
#define WF_LEX_COM_ATPROTO_REPO_APPLY_WRITES_KIND "procedure"

/** Create a single new repository record. Requires auth, implemented by PDS. */
#define WF_LEX_COM_ATPROTO_REPO_CREATE_RECORD_NSID "com.atproto.repo.createRecord"
#define WF_LEX_COM_ATPROTO_REPO_CREATE_RECORD_KIND "procedure"

#define WF_LEX_COM_ATPROTO_REPO_DEFS_NSID "com.atproto.repo.defs"
#define WF_LEX_COM_ATPROTO_REPO_DEFS_KIND "definition"

/** Delete a repository record, or ensure it doesn't exist. Requires auth, implemented by PDS. */
#define WF_LEX_COM_ATPROTO_REPO_DELETE_RECORD_NSID "com.atproto.repo.deleteRecord"
#define WF_LEX_COM_ATPROTO_REPO_DELETE_RECORD_KIND "procedure"

/** Get information about an account and repository, including the list of collections. Does not require auth. */
#define WF_LEX_COM_ATPROTO_REPO_DESCRIBE_REPO_NSID "com.atproto.repo.describeRepo"
#define WF_LEX_COM_ATPROTO_REPO_DESCRIBE_REPO_KIND "query"

/** Get a single record from a repository. Does not require auth. */
#define WF_LEX_COM_ATPROTO_REPO_GET_RECORD_NSID "com.atproto.repo.getRecord"
#define WF_LEX_COM_ATPROTO_REPO_GET_RECORD_KIND "query"

/** List a range of records in a repository, matching a specific collection. Does not require auth. */
#define WF_LEX_COM_ATPROTO_REPO_LIST_RECORDS_NSID "com.atproto.repo.listRecords"
#define WF_LEX_COM_ATPROTO_REPO_LIST_RECORDS_KIND "query"

/** Write a repository record, creating or updating it as needed. Requires auth, implemented by PDS. */
#define WF_LEX_COM_ATPROTO_REPO_PUT_RECORD_NSID "com.atproto.repo.putRecord"
#define WF_LEX_COM_ATPROTO_REPO_PUT_RECORD_KIND "procedure"

#define WF_LEX_COM_ATPROTO_REPO_STRONG_REF_NSID "com.atproto.repo.strongRef"
#define WF_LEX_COM_ATPROTO_REPO_STRONG_REF_KIND "object"

/** Upload a new blob, to be referenced from a repository record. The blob will be deleted if it is not referenced within a time window (eg, minutes). Blob restrictions (mimetype, size, etc) are enforced when the reference is created. Requires auth, implemented by PDS. */
#define WF_LEX_COM_ATPROTO_REPO_UPLOAD_BLOB_NSID "com.atproto.repo.uploadBlob"
#define WF_LEX_COM_ATPROTO_REPO_UPLOAD_BLOB_KIND "procedure"

/** Create an authentication session. */
#define WF_LEX_COM_ATPROTO_SERVER_CREATE_SESSION_NSID "com.atproto.server.createSession"
#define WF_LEX_COM_ATPROTO_SERVER_CREATE_SESSION_KIND "procedure"

/** Delete the current session. Requires auth using the 'refreshJwt' (not the 'accessJwt'). */
#define WF_LEX_COM_ATPROTO_SERVER_DELETE_SESSION_NSID "com.atproto.server.deleteSession"
#define WF_LEX_COM_ATPROTO_SERVER_DELETE_SESSION_KIND "procedure"

/** Get information about the current auth session. Requires auth. */
#define WF_LEX_COM_ATPROTO_SERVER_GET_SESSION_NSID "com.atproto.server.getSession"
#define WF_LEX_COM_ATPROTO_SERVER_GET_SESSION_KIND "query"

/** Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt'). */
#define WF_LEX_COM_ATPROTO_SERVER_REFRESH_SESSION_NSID "com.atproto.server.refreshSession"
#define WF_LEX_COM_ATPROTO_SERVER_REFRESH_SESSION_KIND "procedure"

/** Download a repository export as CAR file. Optionally only a 'diff' since a previous revision. Does not require auth; implemented by PDS. */
#define WF_LEX_COM_ATPROTO_SYNC_GET_REPO_NSID "com.atproto.sync.getRepo"
#define WF_LEX_COM_ATPROTO_SYNC_GET_REPO_KIND "query"

typedef struct wf_lex_com_atproto_identity_resolve_handle_main_output wf_lex_com_atproto_identity_resolve_handle_main_output;
typedef struct wf_lex_com_atproto_identity_resolve_handle_main_params wf_lex_com_atproto_identity_resolve_handle_main_params;
typedef struct wf_lex_com_atproto_repo_apply_writes_create wf_lex_com_atproto_repo_apply_writes_create;
typedef struct wf_lex_com_atproto_repo_apply_writes_create_result wf_lex_com_atproto_repo_apply_writes_create_result;
typedef struct wf_lex_com_atproto_repo_apply_writes_delete wf_lex_com_atproto_repo_apply_writes_delete;
typedef struct wf_lex_com_atproto_repo_apply_writes_delete_result wf_lex_com_atproto_repo_apply_writes_delete_result;
typedef struct wf_lex_com_atproto_repo_apply_writes_main_input wf_lex_com_atproto_repo_apply_writes_main_input;
typedef struct wf_lex_com_atproto_repo_apply_writes_main_output wf_lex_com_atproto_repo_apply_writes_main_output;
typedef struct wf_lex_com_atproto_repo_apply_writes_update wf_lex_com_atproto_repo_apply_writes_update;
typedef struct wf_lex_com_atproto_repo_apply_writes_update_result wf_lex_com_atproto_repo_apply_writes_update_result;
typedef struct wf_lex_com_atproto_repo_create_record_main_input wf_lex_com_atproto_repo_create_record_main_input;
typedef struct wf_lex_com_atproto_repo_create_record_main_output wf_lex_com_atproto_repo_create_record_main_output;
typedef struct wf_lex_com_atproto_repo_defs_commit_meta wf_lex_com_atproto_repo_defs_commit_meta;
typedef struct wf_lex_com_atproto_repo_delete_record_main_input wf_lex_com_atproto_repo_delete_record_main_input;
typedef struct wf_lex_com_atproto_repo_delete_record_main_output wf_lex_com_atproto_repo_delete_record_main_output;
typedef struct wf_lex_com_atproto_repo_describe_repo_main_output wf_lex_com_atproto_repo_describe_repo_main_output;
typedef struct wf_lex_com_atproto_repo_describe_repo_main_params wf_lex_com_atproto_repo_describe_repo_main_params;
typedef struct wf_lex_com_atproto_repo_get_record_main_output wf_lex_com_atproto_repo_get_record_main_output;
typedef struct wf_lex_com_atproto_repo_get_record_main_params wf_lex_com_atproto_repo_get_record_main_params;
typedef struct wf_lex_com_atproto_repo_list_records_main_output wf_lex_com_atproto_repo_list_records_main_output;
typedef struct wf_lex_com_atproto_repo_list_records_main_params wf_lex_com_atproto_repo_list_records_main_params;
typedef struct wf_lex_com_atproto_repo_list_records_record wf_lex_com_atproto_repo_list_records_record;
typedef struct wf_lex_com_atproto_repo_put_record_main_input wf_lex_com_atproto_repo_put_record_main_input;
typedef struct wf_lex_com_atproto_repo_put_record_main_output wf_lex_com_atproto_repo_put_record_main_output;
typedef struct wf_lex_com_atproto_repo_strong_ref_main wf_lex_com_atproto_repo_strong_ref_main;
typedef struct wf_lex_com_atproto_repo_upload_blob_main_output wf_lex_com_atproto_repo_upload_blob_main_output;
typedef struct wf_lex_com_atproto_server_create_session_main_input wf_lex_com_atproto_server_create_session_main_input;
typedef struct wf_lex_com_atproto_server_create_session_main_output wf_lex_com_atproto_server_create_session_main_output;
typedef struct wf_lex_com_atproto_server_get_session_main_output wf_lex_com_atproto_server_get_session_main_output;
typedef struct wf_lex_com_atproto_server_refresh_session_main_output wf_lex_com_atproto_server_refresh_session_main_output;
typedef struct wf_lex_com_atproto_sync_get_repo_main_params wf_lex_com_atproto_sync_get_repo_main_params;

typedef struct wf_lex_com_atproto_identity_resolve_handle_main_params {
    /** The handle to resolve. */
    const char * handle;
} wf_lex_com_atproto_identity_resolve_handle_main_params;

typedef struct wf_lex_com_atproto_identity_resolve_handle_main_output {
    const char * did;
} wf_lex_com_atproto_identity_resolve_handle_main_output;

typedef struct wf_lex_com_atproto_repo_apply_writes_main_input {
    /** The handle or DID of the repo (aka, current account). */
    const char * repo;
    /** Can be set to 'false' to skip Lexicon schema validation of record data across all operations, 'true' to require it, or leave unset to validate only for known Lexicons. */
    bool has_validate;
    bool validate;
    WF_LEX_ARRAY(wf_lex_json) writes;
    /** If provided, the entire operation will fail if the current repo commit CID does not match this value. Used to prevent conflicting repo mutations. */
    bool has_swap_commit;
    const char * swap_commit;
} wf_lex_com_atproto_repo_apply_writes_main_input;

typedef struct wf_lex_com_atproto_repo_apply_writes_main_output {
    bool has_commit;
    const wf_lex_com_atproto_repo_defs_commit_meta * commit;
    bool has_results;
    WF_LEX_ARRAY(wf_lex_json) results;
} wf_lex_com_atproto_repo_apply_writes_main_output;

/** Operation which creates a new record. */
typedef struct wf_lex_com_atproto_repo_apply_writes_create {
    const char * collection;
    /** NOTE: maxLength is redundant with record-key format. Keeping it temporarily to ensure backwards compatibility. */
    bool has_rkey;
    const char * rkey;
    wf_lex_json value;
} wf_lex_com_atproto_repo_apply_writes_create;

/** Operation which updates an existing record. */
typedef struct wf_lex_com_atproto_repo_apply_writes_update {
    const char * collection;
    const char * rkey;
    wf_lex_json value;
} wf_lex_com_atproto_repo_apply_writes_update;

/** Operation which deletes an existing record. */
typedef struct wf_lex_com_atproto_repo_apply_writes_delete {
    const char * collection;
    const char * rkey;
} wf_lex_com_atproto_repo_apply_writes_delete;

typedef struct wf_lex_com_atproto_repo_apply_writes_create_result {
    const char * uri;
    const char * cid;
    bool has_validation_status;
    const char * validation_status;
} wf_lex_com_atproto_repo_apply_writes_create_result;

typedef struct wf_lex_com_atproto_repo_apply_writes_update_result {
    const char * uri;
    const char * cid;
    bool has_validation_status;
    const char * validation_status;
} wf_lex_com_atproto_repo_apply_writes_update_result;

typedef struct wf_lex_com_atproto_repo_apply_writes_delete_result {
    unsigned char _unused;
} wf_lex_com_atproto_repo_apply_writes_delete_result;

typedef struct wf_lex_com_atproto_repo_create_record_main_input {
    /** The handle or DID of the repo (aka, current account). */
    const char * repo;
    /** The NSID of the record collection. */
    const char * collection;
    /** The Record Key. */
    bool has_rkey;
    const char * rkey;
    /** Can be set to 'false' to skip Lexicon schema validation of record data, 'true' to require it, or leave unset to validate only for known Lexicons. */
    bool has_validate;
    bool validate;
    /** The record itself. Must contain a $type field. */
    wf_lex_json record;
    /** Compare and swap with the previous commit by CID. */
    bool has_swap_commit;
    const char * swap_commit;
} wf_lex_com_atproto_repo_create_record_main_input;

typedef struct wf_lex_com_atproto_repo_create_record_main_output {
    const char * uri;
    const char * cid;
    bool has_commit;
    const wf_lex_com_atproto_repo_defs_commit_meta * commit;
    bool has_validation_status;
    const char * validation_status;
} wf_lex_com_atproto_repo_create_record_main_output;

typedef struct wf_lex_com_atproto_repo_defs_commit_meta {
    const char * cid;
    const char * rev;
} wf_lex_com_atproto_repo_defs_commit_meta;

typedef struct wf_lex_com_atproto_repo_delete_record_main_input {
    /** The handle or DID of the repo (aka, current account). */
    const char * repo;
    /** The NSID of the record collection. */
    const char * collection;
    /** The Record Key. */
    const char * rkey;
    /** Compare and swap with the previous record by CID. */
    bool has_swap_record;
    const char * swap_record;
    /** Compare and swap with the previous commit by CID. */
    bool has_swap_commit;
    const char * swap_commit;
} wf_lex_com_atproto_repo_delete_record_main_input;

typedef struct wf_lex_com_atproto_repo_delete_record_main_output {
    bool has_commit;
    const wf_lex_com_atproto_repo_defs_commit_meta * commit;
} wf_lex_com_atproto_repo_delete_record_main_output;

typedef struct wf_lex_com_atproto_repo_describe_repo_main_params {
    /** The handle or DID of the repo. */
    const char * repo;
} wf_lex_com_atproto_repo_describe_repo_main_params;

typedef struct wf_lex_com_atproto_repo_describe_repo_main_output {
    const char * handle;
    const char * did;
    /** The complete DID document for this account. */
    wf_lex_json did_doc;
    /** List of all the collections (NSIDs) for which this repo contains at least one record. */
    WF_LEX_ARRAY(const char *) collections;
    /** Indicates if handle is currently valid (resolves bi-directionally) */
    bool handle_is_correct;
} wf_lex_com_atproto_repo_describe_repo_main_output;

typedef struct wf_lex_com_atproto_repo_get_record_main_params {
    /** The handle or DID of the repo. */
    const char * repo;
    /** The NSID of the record collection. */
    const char * collection;
    /** The Record Key. */
    const char * rkey;
    /** The CID of the version of the record. If not specified, then return the most recent version. */
    bool has_cid;
    const char * cid;
} wf_lex_com_atproto_repo_get_record_main_params;

typedef struct wf_lex_com_atproto_repo_get_record_main_output {
    const char * uri;
    bool has_cid;
    const char * cid;
    wf_lex_json value;
} wf_lex_com_atproto_repo_get_record_main_output;

typedef struct wf_lex_com_atproto_repo_list_records_main_params {
    /** The handle or DID of the repo. */
    const char * repo;
    /** The NSID of the record type. */
    const char * collection;
    /** The number of records to return. */
    bool has_limit;
    int64_t limit;
    bool has_cursor;
    const char * cursor;
    /** Flag to reverse the order of the returned records. */
    bool has_reverse;
    bool reverse;
} wf_lex_com_atproto_repo_list_records_main_params;

typedef struct wf_lex_com_atproto_repo_list_records_main_output {
    bool has_cursor;
    const char * cursor;
    WF_LEX_ARRAY(const wf_lex_com_atproto_repo_list_records_record *) records;
} wf_lex_com_atproto_repo_list_records_main_output;

typedef struct wf_lex_com_atproto_repo_list_records_record {
    const char * uri;
    const char * cid;
    wf_lex_json value;
} wf_lex_com_atproto_repo_list_records_record;

typedef struct wf_lex_com_atproto_repo_put_record_main_input {
    /** The handle or DID of the repo (aka, current account). */
    const char * repo;
    /** The NSID of the record collection. */
    const char * collection;
    /** The Record Key. */
    const char * rkey;
    /** Can be set to 'false' to skip Lexicon schema validation of record data, 'true' to require it, or leave unset to validate only for known Lexicons. */
    bool has_validate;
    bool validate;
    /** The record to write. */
    wf_lex_json record;
    /** Compare and swap with the previous record by CID. WARNING: nullable and optional field; may cause problems with golang implementation */
    bool has_swap_record;
    const char * swap_record;
    /** Compare and swap with the previous commit by CID. */
    bool has_swap_commit;
    const char * swap_commit;
} wf_lex_com_atproto_repo_put_record_main_input;

typedef struct wf_lex_com_atproto_repo_put_record_main_output {
    const char * uri;
    const char * cid;
    bool has_commit;
    const wf_lex_com_atproto_repo_defs_commit_meta * commit;
    bool has_validation_status;
    const char * validation_status;
} wf_lex_com_atproto_repo_put_record_main_output;

typedef struct wf_lex_com_atproto_repo_strong_ref_main {
    const char * uri;
    const char * cid;
} wf_lex_com_atproto_repo_strong_ref_main;

typedef struct wf_lex_com_atproto_repo_upload_blob_main_output {
    wf_lex_blob blob;
} wf_lex_com_atproto_repo_upload_blob_main_output;

typedef struct wf_lex_com_atproto_server_create_session_main_input {
    /** Handle or other identifier supported by the server for the authenticating user. */
    const char * identifier;
    const char * password;
    bool has_auth_factor_token;
    const char * auth_factor_token;
    /** When true, instead of throwing error for takendown accounts, a valid response with a narrow scoped token will be returned */
    bool has_allow_takendown;
    bool allow_takendown;
} wf_lex_com_atproto_server_create_session_main_input;

typedef struct wf_lex_com_atproto_server_create_session_main_output {
    const char * access_jwt;
    const char * refresh_jwt;
    const char * handle;
    const char * did;
    bool has_did_doc;
    wf_lex_json did_doc;
    bool has_email;
    const char * email;
    bool has_email_confirmed;
    bool email_confirmed;
    bool has_email_auth_factor;
    bool email_auth_factor;
    bool has_active;
    bool active;
    /** If active=false, this optional field indicates a possible reason for why the account is not active. If active=false and no status is supplied, then the host makes no claim for why the repository is no longer being hosted. */
    bool has_status;
    const char * status;
} wf_lex_com_atproto_server_create_session_main_output;

typedef struct wf_lex_com_atproto_server_get_session_main_output {
    const char * handle;
    const char * did;
    bool has_did_doc;
    wf_lex_json did_doc;
    bool has_email;
    const char * email;
    bool has_email_confirmed;
    bool email_confirmed;
    bool has_email_auth_factor;
    bool email_auth_factor;
    bool has_active;
    bool active;
    /** If active=false, this optional field indicates a possible reason for why the account is not active. If active=false and no status is supplied, then the host makes no claim for why the repository is no longer being hosted. */
    bool has_status;
    const char * status;
} wf_lex_com_atproto_server_get_session_main_output;

typedef struct wf_lex_com_atproto_server_refresh_session_main_output {
    const char * access_jwt;
    const char * refresh_jwt;
    const char * handle;
    const char * did;
    bool has_did_doc;
    wf_lex_json did_doc;
    bool has_email;
    const char * email;
    bool has_email_confirmed;
    bool email_confirmed;
    bool has_email_auth_factor;
    bool email_auth_factor;
    bool has_active;
    bool active;
    /** Hosting status of the account. If not specified, then assume 'active'. */
    bool has_status;
    const char * status;
} wf_lex_com_atproto_server_refresh_session_main_output;

typedef struct wf_lex_com_atproto_sync_get_repo_main_params {
    /** The DID of the repo. */
    const char * did;
    /** The revision ('rev') of the repo to create a diff from. */
    bool has_since;
    const char * since;
} wf_lex_com_atproto_sync_get_repo_main_params;

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_identity_resolve_handle_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_identity_resolve_handle_main_output **out_value);
void wf_lex_com_atproto_identity_resolve_handle_main_output_free(wf_lex_com_atproto_identity_resolve_handle_main_output *value);
wf_status wf_lex_com_atproto_identity_resolve_handle_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_identity_resolve_handle_main_params *params, wf_response *out);
wf_status wf_lex_com_atproto_identity_resolve_handle_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_identity_resolve_handle_main_params *params, wf_response *out);

wf_status wf_lex_com_atproto_repo_apply_writes_main_input_encode_json(
    const wf_lex_com_atproto_repo_apply_writes_main_input *value, char **out_json);
/** Free JSON returned by the matching encoder. */
void wf_lex_com_atproto_repo_apply_writes_main_json_free(char *json);
/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_apply_writes_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_apply_writes_main_output **out_value);
void wf_lex_com_atproto_repo_apply_writes_main_output_free(wf_lex_com_atproto_repo_apply_writes_main_output *value);
wf_status wf_lex_com_atproto_repo_apply_writes_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_apply_writes_main_input *input, wf_response *out);
wf_status wf_lex_com_atproto_repo_apply_writes_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_apply_writes_main_input *input, wf_response *out);

wf_status wf_lex_com_atproto_repo_create_record_main_input_encode_json(
    const wf_lex_com_atproto_repo_create_record_main_input *value, char **out_json);
/** Free JSON returned by the matching encoder. */
void wf_lex_com_atproto_repo_create_record_main_json_free(char *json);
/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_create_record_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_create_record_main_output **out_value);
void wf_lex_com_atproto_repo_create_record_main_output_free(wf_lex_com_atproto_repo_create_record_main_output *value);
wf_status wf_lex_com_atproto_repo_create_record_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_create_record_main_input *input, wf_response *out);
wf_status wf_lex_com_atproto_repo_create_record_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_create_record_main_input *input, wf_response *out);

wf_status wf_lex_com_atproto_repo_delete_record_main_input_encode_json(
    const wf_lex_com_atproto_repo_delete_record_main_input *value, char **out_json);
/** Free JSON returned by the matching encoder. */
void wf_lex_com_atproto_repo_delete_record_main_json_free(char *json);
/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_delete_record_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_delete_record_main_output **out_value);
void wf_lex_com_atproto_repo_delete_record_main_output_free(wf_lex_com_atproto_repo_delete_record_main_output *value);
wf_status wf_lex_com_atproto_repo_delete_record_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_delete_record_main_input *input, wf_response *out);
wf_status wf_lex_com_atproto_repo_delete_record_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_delete_record_main_input *input, wf_response *out);

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_describe_repo_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_describe_repo_main_output **out_value);
void wf_lex_com_atproto_repo_describe_repo_main_output_free(wf_lex_com_atproto_repo_describe_repo_main_output *value);
wf_status wf_lex_com_atproto_repo_describe_repo_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_describe_repo_main_params *params, wf_response *out);
wf_status wf_lex_com_atproto_repo_describe_repo_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_describe_repo_main_params *params, wf_response *out);

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_get_record_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_get_record_main_output **out_value);
void wf_lex_com_atproto_repo_get_record_main_output_free(wf_lex_com_atproto_repo_get_record_main_output *value);
wf_status wf_lex_com_atproto_repo_get_record_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_get_record_main_params *params, wf_response *out);
wf_status wf_lex_com_atproto_repo_get_record_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_get_record_main_params *params, wf_response *out);

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_list_records_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_list_records_main_output **out_value);
void wf_lex_com_atproto_repo_list_records_main_output_free(wf_lex_com_atproto_repo_list_records_main_output *value);
wf_status wf_lex_com_atproto_repo_list_records_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_list_records_main_params *params, wf_response *out);
wf_status wf_lex_com_atproto_repo_list_records_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_list_records_main_params *params, wf_response *out);

wf_status wf_lex_com_atproto_repo_put_record_main_input_encode_json(
    const wf_lex_com_atproto_repo_put_record_main_input *value, char **out_json);
/** Free JSON returned by the matching encoder. */
void wf_lex_com_atproto_repo_put_record_main_json_free(char *json);
/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_put_record_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_put_record_main_output **out_value);
void wf_lex_com_atproto_repo_put_record_main_output_free(wf_lex_com_atproto_repo_put_record_main_output *value);
wf_status wf_lex_com_atproto_repo_put_record_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_repo_put_record_main_input *input, wf_response *out);
wf_status wf_lex_com_atproto_repo_put_record_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_repo_put_record_main_input *input, wf_response *out);

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_repo_upload_blob_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_repo_upload_blob_main_output **out_value);
void wf_lex_com_atproto_repo_upload_blob_main_output_free(wf_lex_com_atproto_repo_upload_blob_main_output *value);
wf_status wf_lex_com_atproto_repo_upload_blob_main_call(wf_xrpc_client *client, wf_response *out);
wf_status wf_lex_com_atproto_repo_upload_blob_main_call_auth(wf_auth_client *client, wf_response *out);

wf_status wf_lex_com_atproto_server_create_session_main_input_encode_json(
    const wf_lex_com_atproto_server_create_session_main_input *value, char **out_json);
/** Free JSON returned by the matching encoder. */
void wf_lex_com_atproto_server_create_session_main_json_free(char *json);
/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_server_create_session_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_server_create_session_main_output **out_value);
void wf_lex_com_atproto_server_create_session_main_output_free(wf_lex_com_atproto_server_create_session_main_output *value);
wf_status wf_lex_com_atproto_server_create_session_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_server_create_session_main_input *input, wf_response *out);
wf_status wf_lex_com_atproto_server_create_session_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_server_create_session_main_input *input, wf_response *out);

wf_status wf_lex_com_atproto_server_delete_session_main_call(wf_xrpc_client *client, wf_response *out);
wf_status wf_lex_com_atproto_server_delete_session_main_call_auth(wf_auth_client *client, wf_response *out);

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_server_get_session_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_server_get_session_main_output **out_value);
void wf_lex_com_atproto_server_get_session_main_output_free(wf_lex_com_atproto_server_get_session_main_output *value);
wf_status wf_lex_com_atproto_server_get_session_main_call(wf_xrpc_client *client,
    wf_response *out);
wf_status wf_lex_com_atproto_server_get_session_main_call_auth(wf_auth_client *client,
    wf_response *out);

/** Decode an owning output value; free it with the matching function. */
wf_status wf_lex_com_atproto_server_refresh_session_main_output_decode_json(
    const char *json, size_t length, wf_lex_com_atproto_server_refresh_session_main_output **out_value);
void wf_lex_com_atproto_server_refresh_session_main_output_free(wf_lex_com_atproto_server_refresh_session_main_output *value);
wf_status wf_lex_com_atproto_server_refresh_session_main_call(wf_xrpc_client *client, wf_response *out);
wf_status wf_lex_com_atproto_server_refresh_session_main_call_auth(wf_auth_client *client, wf_response *out);

wf_status wf_lex_com_atproto_sync_get_repo_main_call(wf_xrpc_client *client,
    const wf_lex_com_atproto_sync_get_repo_main_params *params, wf_response *out);
wf_status wf_lex_com_atproto_sync_get_repo_main_call_auth(wf_auth_client *client,
    const wf_lex_com_atproto_sync_get_repo_main_params *params, wf_response *out);

#undef WF_LEX_ARRAY

#ifdef __cplusplus
}
#endif

#endif /* WOLFRAM_ATPROTO_LEX_H */
