#ifndef WOLFRAM_VERSION_H
#define WOLFRAM_VERSION_H

#define WOLFRAM_VERSION_MAJOR 0
#define WOLFRAM_VERSION_MINOR 1
#define WOLFRAM_VERSION_PATCH 0
#define WOLFRAM_VERSION_STRING "0.1.0"

#endif /* WOLFRAM_VERSION_H */
