#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <regex>
#include <set>
#include <vector>
#include <algorithm>

namespace fs = std::filesystem;

std::string to_pascal_case(const std::string &snake) {
    std::string result;
    size_t start = 0;
    while (start <= snake.size()) {
        size_t end = snake.find('_', start);
        if (end == std::string::npos) end = snake.size();
        if (end > start) {
            result += std::toupper(snake[start]);
            for (size_t i = start + 1; i < end; ++i)
                result += std::tolower(snake[i]);
        }
        if (end == snake.size()) break;
        start = end + 1;
    }
    return result;
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        std::cerr
            << "Usage: gen_safehandles <wolfram-include-dir> <output.cs>\n";
        return 1;
    }

    fs::path inc_dir(argv[1]);
    fs::path out_path(argv[2]);

    // Match `void wf_<T>_free(wf_<T> *name)`
    std::regex header_re(
        R"(void\s+wf_([A-Za-z0-9_]+)_free\s*\(\s*wf_\1\s*\*\s*\w+\s*\))");

    // Also match `void wf_<T>_free(wf_<T> *name, size_t n)` for array free
    // functions - skip these
    std::regex array_free_re(
        R"(void\s+wf_([A-Za-z0-9_]+)_free\s*\(\s*wf_\1\s*\*\s*\w+\s*,)");

    // Types that have hand-written SafeHandles in the managed tier
    std::set<std::string> skip_types = {"xrpc_client"};

    std::map<std::string, std::string> types; // type -> free function name
    std::set<std::string> array_types;
    int header_count = 0;

    for (const auto &entry : fs::recursive_directory_iterator(inc_dir)) {
        if (entry.path().extension() != ".h") continue;
        if (entry.path().string().find("json-enhanced") != std::string::npos)
            continue;
        header_count++;

        std::ifstream file(entry.path());
        std::string text((std::istreambuf_iterator<char>(file)),
                         std::istreambuf_iterator<char>());

        // Collect array-free types (to exclude from SafeHandle generation)
        {
            std::smatch match;
            std::string::const_iterator search_start(text.cbegin());
            while (std::regex_search(search_start, text.cend(), match,
                                     array_free_re)) {
                array_types.insert(match[1].str());
                search_start = match.suffix().first;
            }
        }

        {
            std::smatch match;
            std::string::const_iterator search_start(text.cbegin());
            while (std::regex_search(search_start, text.cend(), match,
                                     header_re)) {
                std::string t = match[1].str();
                if (types.find(t) == types.end() &&
                    array_types.find(t) == array_types.end() &&
                    skip_types.find(t) == skip_types.end()) {
                    types[t] = "wf_" + t + "_free";
                }
                search_start = match.suffix().first;
            }
        }
    }

    std::vector<std::string> lines;
    lines.emplace_back(
        "// Generated by tools/gen_safehandles.cpp; do not edit.");
    lines.emplace_back(
        "// SafeHandle subclasses for every wolfram opaque type that has a");
    lines.emplace_back("// `void wf_<T>_free(wf_<T>*)` function. Regenerated "
                       "from the C headers.");
    lines.emplace_back("// Each SafeHandle declares its own [LibraryImport] "
                       "for the free function,");
    lines.emplace_back(
        "// so this file is self-contained and does not depend on Raw.cs.");
    lines.emplace_back("");
    lines.emplace_back("using System;");
    lines.emplace_back("using System.Runtime.InteropServices;");
    lines.emplace_back("");
    lines.emplace_back("namespace Wolfram.Interop;");
    lines.emplace_back("");

    std::vector<std::string> sorted_types;
    for (const auto &[t, _] : types) {
        sorted_types.push_back(t);
    }
    std::sort(sorted_types.begin(), sorted_types.end());

    for (const auto &t : sorted_types) {
        std::string pascal = to_pascal_case(t);
        std::string free_fn = types.at(t);
        lines.emplace_back("/// <summary>");
        lines.emplace_back("/// SafeHandle owning a <c>" + t +
                           "</c>. Released via");
        lines.emplace_back("/// <c>" + free_fn +
                           "</c> when disposed or finalized.");
        lines.emplace_back("/// </summary>");
        lines.emplace_back("internal sealed partial class " + pascal +
                           "Handle : SafeHandle");
        lines.emplace_back("{");
        lines.emplace_back("    public " + pascal +
                           "Handle(IntPtr ptr, bool ownsHandle = true)");
        lines.emplace_back(
            "        : base(IntPtr.Zero, ownsHandle) => SetHandle(ptr);");
        lines.emplace_back("");
        lines.emplace_back(
            "    public override bool IsInvalid => handle == IntPtr.Zero;");
        lines.emplace_back("");
        lines.emplace_back("    protected override bool ReleaseHandle()");
        lines.emplace_back("    {");
        lines.emplace_back("        " + free_fn + "(handle);");
        lines.emplace_back("        return true;");
        lines.emplace_back("    }");
        lines.emplace_back("");
        lines.emplace_back("    [LibraryImport(\"wolfram\")]");
        lines.emplace_back("    private static partial void " + free_fn +
                           "(IntPtr ptr);");
        lines.emplace_back("}");
        lines.emplace_back("");
    }

    // Remove trailing blank line
    if (!lines.empty() && lines.back().empty()) {
        lines.pop_back();
    }
    lines.emplace_back("");

    fs::create_directories(out_path.parent_path());
    std::ofstream out(out_path);
    for (const auto &line : lines) {
        out << line << "\n";
    }

    std::cout << "wrote " << out_path << ": " << types.size()
              << " SafeHandle types from " << header_count << " headers\n";
    return 0;
}
