#!/usr/bin/env python3
"""Generate C# SafeHandle subclasses from wolfram's wf_*_free set.

Scans the wolfram C public headers for ``void wf_<T>_free(wf_<T> *...)`` and
emits a C# source file declaring ``SafeHandle`` subclasses that call the
matching free function in their ``ReleaseHandle`` override. Each SafeHandle
is self-contained: it declares its own ``[LibraryImport]`` for the free
function, so it does not depend on the hand-written ``Raw.cs`` having a
matching declaration.

This mirrors the C++ gen_owners.py approach: the C headers are the single
source of truth, and the wrapper layer is generated from them.

Usage:
    python3 tools/gen_safehandles.py <wolfram-include-dir> <output.cs>
"""
import re
import sys
from pathlib import Path

# Match `void wf_<T>_free(wf_<T> *name)`. The backreference ensures the freed
# type matches the function prefix. Excludes `wf_*_json_free(char*)` (strings)
# and `wf_*_free(char*)` string free functions.
HEADER_RE = re.compile(
    r"void\s+wf_([A-Za-z0-9_]+)_free\s*\(\s*wf_\1\s*\*\s*\w+\s*\)"
)

# Also match `void wf_<T>_free(wf_<T> *name, size_t n)` for array free functions
# — these are not SafeHandle-able (they need a count), so we skip them.
ARRAY_FREE_RE = re.compile(
    r"void\s+wf_([A-Za-z0-9_]+)_free\s*\(\s*wf_\1\s*\*\s*\w+\s*,"
)


def to_pascal_case(snake: str) -> str:
    """Convert ``snake_case`` to ``PascalCase``."""
    return "".join(part.capitalize() for part in snake.split("_") if part)


def main() -> int:
    inc_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "../../include/wolfram")
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("SafeHandles/SafeHandles.generated.cs")

    # Types that have hand-written SafeHandles in the managed tier.
    # The generator skips these to avoid duplicate declarations.
    skip_types: set[str] = {
        "xrpc_client",  # SafeHandle/XrpcClientHandle.cs (public, used by WolframClient)
    }

    types: dict[str, str] = {}  # type_name -> free_function_name
    array_types: set[str] = set()
    header_count = 0

    for h in sorted(inc_dir.rglob("*.h")):
        if "json-enhanced" in h.parts:
            continue
        header_count += 1
        text = h.read_text(encoding="utf-8", errors="ignore")

        # Collect array-free types (to exclude them from SafeHandle generation)
        for m in ARRAY_FREE_RE.finditer(text):
            array_types.add(m.group(1))

        for m in HEADER_RE.finditer(text):
            t = m.group(1)
            if t not in types and t not in array_types and t not in skip_types:
                types[t] = f"wf_{t}_free"

    lines = [
        "// Generated by tools/gen_safehandles.py; do not edit.",
        "// SafeHandle subclasses for every wolfram opaque type that has a",
        "// `void wf_<T>_free(wf_<T>*)` function. Regenerated from the C headers.",
        "// Each SafeHandle declares its own [LibraryImport] for the free function,",
        "// so this file is self-contained and does not depend on Raw.cs.",
        "",
        "using System;",
        "using System.Runtime.InteropServices;",
        "",
        "namespace Wolfram.Interop;",
        "",
    ]

    for t in sorted(types):
        pascal = to_pascal_case(t)
        free_fn = types[t]
        lines += [
            f"/// <summary>",
            f"/// SafeHandle owning a <c>{t}</c>. Released via",
            f"/// <c>{free_fn}</c> when disposed or finalized.",
            f"/// </summary>",
            f"internal sealed partial class {pascal}Handle : SafeHandle",
            f"{{",
            f"    public {pascal}Handle(IntPtr ptr, bool ownsHandle = true)",
            f"        : base(IntPtr.Zero, ownsHandle) => SetHandle(ptr);",
            f"",
            f"    public override bool IsInvalid => handle == IntPtr.Zero;",
            f"",
            f"    protected override bool ReleaseHandle()",
            f"    {{",
            f"        {free_fn}(handle);",
            f"        return true;",
            f"    }}",
            f"",
            f"    [LibraryImport(\"wolfram\")]",
            f"    private static partial void {free_fn}(IntPtr ptr);",
            f"}}",
            f"",
        ]

    # Remove trailing blank line
    if lines and lines[-1] == "":
        lines.pop()

    lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}: {len(types)} SafeHandle types from {header_count} headers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
