/*
 * ed25519.c -- Ed25519 verification (see ed25519.h).
 *
 * Field and group arithmetic follow TweetNaCl (D. J. Bernstein et al., public
 * domain): radix 2^16 limbs in int64, no table lookups indexed by secrets. The
 * curve constants (d, the base point, sqrt(-1)) are derived at first use from
 * their definitions instead of being typed in, and the SHA-512 constants are
 * the fractional parts of the cube and square roots of the first primes
 * (FIPS 180-4), generated by script and checked against hashlib.
 */

#include "wolfram/ed25519.h"

#include <stdint.h>
#include <string.h>

typedef int64_t i64;
typedef uint64_t u64;
typedef unsigned char u8;
typedef i64 gf[16];

/* ---- SHA-512 ---------------------------------------------------------- */

static const u64 K512[80] = {
    0x428a2f98d728ae22ULL, 0x7137449123ef65cdULL, 0xb5c0fbcfec4d3b2fULL,
    0xe9b5dba58189dbbcULL, 0x3956c25bf348b538ULL, 0x59f111f1b605d019ULL,
    0x923f82a4af194f9bULL, 0xab1c5ed5da6d8118ULL, 0xd807aa98a3030242ULL,
    0x12835b0145706fbeULL, 0x243185be4ee4b28cULL, 0x550c7dc3d5ffb4e2ULL,
    0x72be5d74f27b896fULL, 0x80deb1fe3b1696b1ULL, 0x9bdc06a725c71235ULL,
    0xc19bf174cf692694ULL, 0xe49b69c19ef14ad2ULL, 0xefbe4786384f25e3ULL,
    0x0fc19dc68b8cd5b5ULL, 0x240ca1cc77ac9c65ULL, 0x2de92c6f592b0275ULL,
    0x4a7484aa6ea6e483ULL, 0x5cb0a9dcbd41fbd4ULL, 0x76f988da831153b5ULL,
    0x983e5152ee66dfabULL, 0xa831c66d2db43210ULL, 0xb00327c898fb213fULL,
    0xbf597fc7beef0ee4ULL, 0xc6e00bf33da88fc2ULL, 0xd5a79147930aa725ULL,
    0x06ca6351e003826fULL, 0x142929670a0e6e70ULL, 0x27b70a8546d22ffcULL,
    0x2e1b21385c26c926ULL, 0x4d2c6dfc5ac42aedULL, 0x53380d139d95b3dfULL,
    0x650a73548baf63deULL, 0x766a0abb3c77b2a8ULL, 0x81c2c92e47edaee6ULL,
    0x92722c851482353bULL, 0xa2bfe8a14cf10364ULL, 0xa81a664bbc423001ULL,
    0xc24b8b70d0f89791ULL, 0xc76c51a30654be30ULL, 0xd192e819d6ef5218ULL,
    0xd69906245565a910ULL, 0xf40e35855771202aULL, 0x106aa07032bbd1b8ULL,
    0x19a4c116b8d2d0c8ULL, 0x1e376c085141ab53ULL, 0x2748774cdf8eeb99ULL,
    0x34b0bcb5e19b48a8ULL, 0x391c0cb3c5c95a63ULL, 0x4ed8aa4ae3418acbULL,
    0x5b9cca4f7763e373ULL, 0x682e6ff3d6b2b8a3ULL, 0x748f82ee5defb2fcULL,
    0x78a5636f43172f60ULL, 0x84c87814a1f0ab72ULL, 0x8cc702081a6439ecULL,
    0x90befffa23631e28ULL, 0xa4506cebde82bde9ULL, 0xbef9a3f7b2c67915ULL,
    0xc67178f2e372532bULL, 0xca273eceea26619cULL, 0xd186b8c721c0c207ULL,
    0xeada7dd6cde0eb1eULL, 0xf57d4f7fee6ed178ULL, 0x06f067aa72176fbaULL,
    0x0a637dc5a2c898a6ULL, 0x113f9804bef90daeULL, 0x1b710b35131c471bULL,
    0x28db77f523047d84ULL, 0x32caab7b40c72493ULL, 0x3c9ebe0a15c9bebcULL,
    0x431d67c49c100d4cULL, 0x4cc5d4becb3e42b6ULL, 0x597f299cfc657e2aULL,
    0x5fcb6fab3ad6faecULL, 0x6c44198c4a475817ULL,
};

static const u64 H512[8] = {
    0x6a09e667f3bcc908ULL, 0xbb67ae8584caa73bULL, 0x3c6ef372fe94f82bULL,
    0xa54ff53a5f1d36f1ULL, 0x510e527fade682d1ULL, 0x9b05688c2b3e6c1fULL,
    0x1f83d9abfb41bd6bULL, 0x5be0cd19137e2179ULL,
};

#define ROR(x, n) (((x) >> (n)) | ((x) << (64 - (n))))

static void sha512_block(u64 st[8], const u8 *p) {
    u64 w[80], a, b, c, d, e, f, g, h, t1, t2;
    int i;

    for (i = 0; i < 16; i++) {
        int j;
        w[i] = 0;
        for (j = 0; j < 8; j++) w[i] = (w[i] << 8) | p[i * 8 + j];
    }
    for (i = 16; i < 80; i++) {
        u64 s0 = ROR(w[i - 15], 1) ^ ROR(w[i - 15], 8) ^ (w[i - 15] >> 7);
        u64 s1 = ROR(w[i - 2], 19) ^ ROR(w[i - 2], 61) ^ (w[i - 2] >> 6);
        w[i] = w[i - 16] + s0 + w[i - 7] + s1;
    }
    a = st[0];
    b = st[1];
    c = st[2];
    d = st[3];
    e = st[4];
    f = st[5];
    g = st[6];
    h = st[7];
    for (i = 0; i < 80; i++) {
        t1 = h + (ROR(e, 14) ^ ROR(e, 18) ^ ROR(e, 41)) + ((e & f) ^ (~e & g)) +
             K512[i] + w[i];
        t2 = (ROR(a, 28) ^ ROR(a, 34) ^ ROR(a, 39)) +
             ((a & b) ^ (a & c) ^ (b & c));
        h = g;
        g = f;
        f = e;
        e = d + t1;
        d = c;
        c = b;
        b = a;
        a = t1 + t2;
    }
    st[0] += a;
    st[1] += b;
    st[2] += c;
    st[3] += d;
    st[4] += e;
    st[5] += f;
    st[6] += g;
    st[7] += h;
}

/* SHA-512 of up to three buffers concatenated, so verify can hash
 * R || A || M without copying the message. */
static void sha512_3(u8 out[64], const u8 *p1, size_t n1, const u8 *p2,
                     size_t n2, const u8 *p3, size_t n3) {
    u64 st[8];
    u8 buf[128];
    size_t fill = 0, total = n1 + n2 + n3, i;
    const u8 *parts[3];
    size_t lens[3];
    int k;

    parts[0] = p1;
    parts[1] = p2;
    parts[2] = p3;
    lens[0] = n1;
    lens[1] = n2;
    lens[2] = n3;
    memcpy(st, H512, sizeof st);
    for (k = 0; k < 3; k++) {
        const u8 *p = parts[k];
        size_t n = lens[k];
        while (n > 0) {
            size_t take = 128 - fill;
            if (take > n) take = n;
            memcpy(buf + fill, p, take);
            fill += take;
            p += take;
            n -= take;
            if (fill == 128) {
                sha512_block(st, buf);
                fill = 0;
            }
        }
    }
    buf[fill++] = 0x80;
    if (fill > 112) {
        memset(buf + fill, 0, 128 - fill);
        sha512_block(st, buf);
        fill = 0;
    }
    memset(buf + fill, 0, 128 - fill);
    /* 128-bit big-endian bit length; the high 64 bits stay zero (the buffer
     * was zeroed above), which holds for any message under 2^61 bytes. */
    {
        u64 bits = (u64)total * 8;
        for (i = 0; i < 8; i++) buf[120 + i] = (u8)(bits >> (56 - 8 * i));
    }
    sha512_block(st, buf);
    for (i = 0; i < 8; i++) {
        int j;
        for (j = 0; j < 8; j++) out[i * 8 + j] = (u8)(st[i] >> (56 - 8 * j));
    }
}

/* ---- field arithmetic mod 2^255 - 19 --------------------------------- */

static const gf gf0 = {0}, gf1 = {1};

static void set25519(gf r, const gf a) {
    int i;
    for (i = 0; i < 16; i++) r[i] = a[i];
}

static void car25519(gf o) {
    int i;
    i64 c;
    for (i = 0; i < 16; i++) {
        o[i] += (i64)1 << 16;
        c = o[i] >> 16;
        o[(i + 1) * (i < 15)] += c - 1 + 37 * (c - 1) * (i == 15);
        o[i] -= c * 65536; /* not c << 16: c can be negative */
    }
}

static void sel25519(gf p, gf q, int b) {
    i64 t, c = ~((i64)b - 1);
    int i;
    for (i = 0; i < 16; i++) {
        t = c & (p[i] ^ q[i]);
        p[i] ^= t;
        q[i] ^= t;
    }
}

static void pack25519(u8 *o, const gf n) {
    int i, j, b;
    gf m, t;
    for (i = 0; i < 16; i++) t[i] = n[i];
    car25519(t);
    car25519(t);
    car25519(t);
    for (j = 0; j < 2; j++) {
        m[0] = t[0] - 0xffed;
        for (i = 1; i < 15; i++) {
            m[i] = t[i] - 0xffff - ((m[i - 1] >> 16) & 1);
            m[i - 1] &= 0xffff;
        }
        m[15] = t[15] - 0x7fff - ((m[14] >> 16) & 1);
        b = (int)((m[15] >> 16) & 1);
        m[14] &= 0xffff;
        sel25519(t, m, 1 - b);
    }
    for (i = 0; i < 16; i++) {
        o[2 * i] = (u8)(t[i] & 0xff);
        o[2 * i + 1] = (u8)(t[i] >> 8);
    }
}

static int neq25519(const gf a, const gf b) {
    u8 c[32], d[32];
    unsigned diff = 0;
    int i;
    pack25519(c, a);
    pack25519(d, b);
    for (i = 0; i < 32; i++) diff |= (unsigned)(c[i] ^ d[i]);
    return diff != 0;
}

static int par25519(const gf a) {
    u8 d[32];
    pack25519(d, a);
    return d[0] & 1;
}

static void unpack25519(gf o, const u8 *n) {
    int i;
    for (i = 0; i < 16; i++) o[i] = n[2 * i] + ((i64)n[2 * i + 1] << 8);
    o[15] &= 0x7fff;
}

static void A(gf o, const gf a, const gf b) {
    int i;
    for (i = 0; i < 16; i++) o[i] = a[i] + b[i];
}

static void Z(gf o, const gf a, const gf b) {
    int i;
    for (i = 0; i < 16; i++) o[i] = a[i] - b[i];
}

static void M(gf o, const gf a, const gf b) {
    i64 t[31];
    int i, j;
    for (i = 0; i < 31; i++) t[i] = 0;
    for (i = 0; i < 16; i++)
        for (j = 0; j < 16; j++) t[i + j] += a[i] * b[j];
    for (i = 0; i < 15; i++) t[i] += 38 * t[i + 16];
    for (i = 0; i < 16; i++) o[i] = t[i];
    car25519(o);
    car25519(o);
}

static void S(gf o, const gf a) {
    M(o, a, a);
}

/* o = i^(2^255 - 21), the inverse. */
static void inv25519(gf o, const gf i) {
    gf c;
    int a;
    for (a = 0; a < 16; a++) c[a] = i[a];
    for (a = 253; a >= 0; a--) {
        S(c, c);
        if (a != 2 && a != 4) M(c, c, i);
    }
    for (a = 0; a < 16; a++) o[a] = c[a];
}

/* o = i^(2^252 - 3). */
static void pow2523(gf o, const gf i) {
    gf c;
    int a;
    for (a = 0; a < 16; a++) c[a] = i[a];
    for (a = 250; a >= 0; a--) {
        S(c, c);
        if (a != 1) M(c, c, i);
    }
    for (a = 0; a < 16; a++) o[a] = c[a];
}

/* o = base^e for a 32-byte little-endian exponent (public values only). */
static void pow_bytes(gf o, const gf base, const u8 e[32]) {
    gf r;
    int i;
    set25519(r, gf1);
    for (i = 255; i >= 0; i--) {
        S(r, r);
        if ((e[i / 8] >> (i & 7)) & 1) M(r, r, base);
    }
    set25519(o, r);
}

/* ---- curve constants, derived once ----------------------------------- */

static gf D, D2, SQRTM1, BX, BY;
static int consts_ready;

static int unpackneg(gf r[4], const u8 p[32]);

static void init_consts(void) {
    gf a, b, t;
    u8 e[32], by[32];
    int i;

    if (consts_ready) return;

    /* d = -121665 / 121666 */
    set25519(a, gf0);
    a[0] = 121665;
    set25519(b, gf0);
    b[0] = 121666;
    inv25519(t, b);
    M(t, a, t);
    Z(D, gf0, t);
    A(D2, D, D);

    /* sqrt(-1) = 2^((p-1)/4) = 2^(2^253 - 5) */
    for (i = 0; i < 32; i++) e[i] = 0xff;
    e[0] = 0xfb;
    e[31] = 0x1f;
    set25519(a, gf0);
    a[0] = 2;
    pow_bytes(SQRTM1, a, e);

    /* The base point is the point with y = 4/5 and even x; its compressed form
     * is 0x58 followed by 31 bytes of 0x66. Decompress it to get x. */
    by[0] = 0x58;
    for (i = 1; i < 32; i++) by[i] = 0x66;
    {
        gf q[4];
        if (unpackneg(q, by) == 0) {
            Z(BX, gf0, q[0]); /* unpackneg returns -B */
            set25519(BY, q[1]);
        }
    }
    consts_ready = 1;
}

/* ---- group arithmetic (extended coordinates) -------------------------- */

static void point_add(gf p[4], gf q[4]) {
    gf a, b, c, d, t, e, f, g, h;
    Z(a, p[1], p[0]);
    Z(t, q[1], q[0]);
    M(a, a, t);
    A(b, p[0], p[1]);
    A(t, q[0], q[1]);
    M(b, b, t);
    M(c, p[3], q[3]);
    M(c, c, D2);
    M(d, p[2], q[2]);
    A(d, d, d);
    Z(e, b, a);
    Z(f, d, c);
    A(g, d, c);
    A(h, b, a);
    M(p[0], e, f);
    M(p[1], h, g);
    M(p[2], g, f);
    M(p[3], e, h);
}

static void cswap(gf p[4], gf q[4], u8 b) {
    int i;
    for (i = 0; i < 4; i++) sel25519(p[i], q[i], b);
}

static void point_pack(u8 *r, gf p[4]) {
    gf tx, ty, zi;
    inv25519(zi, p[2]);
    M(tx, p[0], zi);
    M(ty, p[1], zi);
    pack25519(r, ty);
    r[31] ^= (u8)(par25519(tx) << 7);
}

static void scalarmult(gf p[4], gf q[4], const u8 *s) {
    int i;
    set25519(p[0], gf0);
    set25519(p[1], gf1);
    set25519(p[2], gf1);
    set25519(p[3], gf0);
    for (i = 255; i >= 0; --i) {
        u8 b = (u8)((s[i / 8] >> (i & 7)) & 1);
        cswap(p, q, b);
        point_add(q, p);
        point_add(p, p);
        cswap(p, q, b);
    }
}

static void scalarbase(gf p[4], const u8 *s) {
    gf q[4];
    set25519(q[0], BX);
    set25519(q[1], BY);
    set25519(q[2], gf1);
    M(q[3], BX, BY);
    scalarmult(p, q, s);
}

/* ---- scalars mod the group order L ----------------------------------- */

static const u64 L[32] = {0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58,
                          0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
                          0,    0,    0,    0,    0,    0,    0,    0,
                          0,    0,    0,    0,    0,    0,    0,    0x10};

static void modL(u8 *r, i64 x[64]) {
    i64 carry, i, j;
    for (i = 63; i >= 32; --i) {
        carry = 0;
        for (j = i - 32; j < i - 12; ++j) {
            x[j] += carry - 16 * x[i] * (i64)L[j - (i - 32)];
            carry = (x[j] + 128) >> 8;
            x[j] -= carry * 256; /* not carry << 8: carry can be negative */
        }
        x[j] += carry;
        x[i] = 0;
    }
    carry = 0;
    for (j = 0; j < 32; j++) {
        x[j] += carry - (x[31] >> 4) * (i64)L[j];
        carry = x[j] >> 8;
        x[j] &= 255;
    }
    for (j = 0; j < 32; j++) x[j] -= carry * (i64)L[j];
    for (i = 0; i < 32; i++) {
        x[i + 1] += x[i] >> 8;
        r[i] = (u8)(x[i] & 255);
    }
}

static void reduce64(u8 *r) {
    i64 x[64];
    int i;
    for (i = 0; i < 64; i++) x[i] = (i64)r[i];
    for (i = 0; i < 64; i++) r[i] = 0;
    modL(r, x);
}

/* S must be < L for the signature to be canonical (RFC 8032 section 5.1.7). */
static int scalar_below_L(const u8 s[32]) {
    int i;
    for (i = 31; i >= 0; i--) {
        if (s[i] < (u8)L[i]) return 1;
        if (s[i] > (u8)L[i]) return 0;
    }
    return 0; /* equal to L */
}

/* Decompress -A: r = (-x, y). Returns nonzero if p is not a curve point. */
static int unpackneg(gf r[4], const u8 p[32]) {
    gf t, chk, num, den, den2, den4, den6;
    set25519(r[2], gf1);
    unpack25519(r[1], p);
    S(num, r[1]);
    M(den, num, D);
    Z(num, num, r[2]);
    A(den, r[2], den);

    S(den2, den);
    S(den4, den2);
    M(den6, den4, den2);
    M(t, den6, num);
    M(t, t, den);

    pow2523(t, t);
    M(t, t, num);
    M(t, t, den);
    M(t, t, den);
    M(r[0], t, den);

    S(chk, r[0]);
    M(chk, chk, den);
    if (neq25519(chk, num)) M(r[0], r[0], SQRTM1);

    S(chk, r[0]);
    M(chk, chk, den);
    if (neq25519(chk, num)) return -1;

    if (par25519(r[0]) == (p[31] >> 7)) Z(r[0], gf0, r[0]);

    M(r[3], r[0], r[1]);
    return 0;
}

wf_status wf_ed25519_verify(const unsigned char sig[WF_ED25519_SIGNATURE_LEN],
                            const void *msg, size_t len,
                            const unsigned char pk[WF_ED25519_PUBLIC_LEN]) {
    u8 t[32], h[64], diff;
    gf p[4], q[4];
    int i;

    if (!sig || !pk || (!msg && len > 0)) return WF_ERR_INVALID_ARG;
    init_consts();
    if (!scalar_below_L(sig + 32)) return WF_ERR_VALIDATION;
    if (unpackneg(q, pk)) return WF_ERR_VALIDATION;

    /* h = SHA-512(R || A || M) mod L */
    sha512_3(h, sig, 32, pk, 32, (const u8 *)msg, len);
    reduce64(h);

    /* R' = [h](-A) + [S]B; the signature is valid iff R' == R. */
    scalarmult(p, q, h);
    scalarbase(q, sig + 32);
    point_add(p, q);
    point_pack(t, p);

    diff = 0;
    for (i = 0; i < 32; i++) diff |= (u8)(sig[i] ^ t[i]);
    return diff == 0 ? WF_OK : WF_ERR_VALIDATION;
}
